GET http://localhost:3001/api/trades

###
POST http://localhost:3001/api/trades
content-type: application/json

{
    "ticker": "AAPL",
    "name": "Apple",
    "qty": 100,
    "price": 155432,
    "type": true,
    "currency_id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
    "exchange_id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
    "cost": 151600,
    "exchange_fees": 1000,
    "date": "2023-01-05",
    "close_id": null
}